USE GRAB;

SET FOREIGN_KEY_CHECKS = 0;

-- 1. Delete from many-to-many relationship and multivalued attribute tables
TRUNCATE TABLE ACCOUNT_COMMUNICATION;

TRUNCATE TABLE TRIP_DISCOUNT;

TRUNCATE TABLE VEHICLE_CATEGORIZATION;

TRUNCATE TABLE ACCOUNT_NOTIFICATION;

-- 2. Delete from tables representing specialization subclasses and weak entities
TRUNCATE TABLE SAVED_LOCATION;

TRUNCATE TABLE PAYMENT_TRANSACTION;

TRUNCATE TABLE COMPLETED_TRIP;

TRUNCATE TABLE CANCELLED_TRIP;

TRUNCATE TABLE ASSIGNED_TRIP;

-- 3. Delete from tables for primary entities and recursive relationships
TRUNCATE TABLE TRIP;

TRUNCATE TABLE VEHICLE;

TRUNCATE TABLE BANK_ACCOUNT;

TRUNCATE TABLE PAYMENT_METHOD;

TRUNCATE TABLE REFERRAL;

TRUNCATE TABLE DRIVER;

TRUNCATE TABLE PASSENGER;

-- 4. Delete from base independent entities and configuration tables
TRUNCATE TABLE USER_NOTIFICATION;

TRUNCATE TABLE TRANSPORT_MODE;

TRUNCATE TABLE DISCOUNT;

TRUNCATE TABLE USER_ACCOUNT;

SET FOREIGN_KEY_CHECKS = 1;