ALTER TABLE DRIVER ADD COLUMN DRIVER_STAR DECIMAL(3, 2) DEFAULT 5;
ALTER TABLE DRIVER ADD CONSTRAINT VALID_STAR_AVERAGE CHECK (DRIVER_STAR BETWEEN 0.0 AND 5.0);

DELIMITER //

-- Helper procedure for calculation
CREATE PROCEDURE RECALCULATE_DRIVER_STAR(IN p_driver_id INT)
BEGIN
    UPDATE DRIVER
    SET DRIVER_STAR = (
        SELECT COALESCE(AVG(CT.RATING_STARS), 5.00)
        FROM COMPLETED_TRIP CT
        JOIN ASSIGNED_TRIP AT ON CT.TRIP_ID = AT.TRIP_ID
        WHERE AT.DRIVER_ID = p_driver_id
    )
    WHERE ACCOUNT_ID = p_driver_id;
END //

CREATE TRIGGER UPDATE_DRIVER_STAR_ON_INSERT
AFTER INSERT ON COMPLETED_TRIP
FOR EACH ROW
BEGIN
    DECLARE v_driver_id INT;
    SELECT DRIVER_ID INTO v_driver_id FROM ASSIGNED_TRIP WHERE TRIP_ID = NEW.TRIP_ID;
    IF v_driver_id IS NOT NULL THEN
        CALL RECALCULATE_DRIVER_STAR(v_driver_id);
    END IF;
END //

CREATE TRIGGER UPDATE_DRIVER_STAR_ON_UPDATE
AFTER UPDATE ON COMPLETED_TRIP
FOR EACH ROW
BEGIN
    DECLARE v_driver_id INT;
    -- Only recalculate if the rating actually changed
    IF NEW.RATING_STARS <> OLD.RATING_STARS THEN
        
        SELECT DRIVER_ID INTO v_driver_id FROM ASSIGNED_TRIP WHERE TRIP_ID = NEW.TRIP_ID;
        IF v_driver_id IS NOT NULL THEN
            CALL RECALCULATE_DRIVER_STAR(v_driver_id);
        END IF;
    END IF;
END //

CREATE TRIGGER UPDATE_DRIVER_STAR_ON_DELETE
AFTER DELETE ON COMPLETED_TRIP
FOR EACH ROW
BEGIN
    DECLARE v_driver_id INT;
    SELECT DRIVER_ID INTO v_driver_id FROM ASSIGNED_TRIP WHERE TRIP_ID = OLD.TRIP_ID;
    IF v_driver_id IS NOT NULL THEN
        CALL RECALCULATE_DRIVER_STAR(v_driver_id);
    END IF;
END //

DELIMITER ;