USE GRAB;

DROP TRIGGER IF EXISTS BEFORE_DRIVER_INSERT;

DROP TRIGGER IF EXISTS BEFORE_PASSENGER_INSERT;

DROP TRIGGER IF EXISTS BEFORE_ASSIGNED_INSERT;

DROP TRIGGER IF EXISTS BEFORE_CANCELLED_INSERT;

DROP TRIGGER IF EXISTS PREVENT_LAST_VEHICLE_DELETE;

DROP TRIGGER IF EXISTS PREVENT_LAST_BANK_ACCOUNT_DELETE;

DROP TRIGGER IF EXISTS PREVENT_LAST_ACCOUNT_NOTIFICATION_DELETE;

DROP TRIGGER IF EXISTS PREVENT_LAST_VEHICLE_CATEGORIZATION_DELETE;

DROP TRIGGER IF EXISTS PREVENT_TRANSACTION_DELETE;

DROP TRIGGER IF EXISTS UPDATE_DRIVER_STAR_ON_INSERT;

DROP TRIGGER IF EXISTS UPDATE_DRIVER_STAR_ON_UPDATE;

DROP TRIGGER IF EXISTS UPDATE_DRIVER_STAR_ON_DELETE;

DROP TRIGGER IF EXISTS TRIP_STATUS_ORDER;

DROP TRIGGER IF EXISTS GRABCOIN_ACCUMULATION;

DROP TRIGGER IF EXISTS GRABCOIN_UPDATE;

-- Constraint 5: Exact Fare Payment Matching
DROP TRIGGER IF EXISTS FARE_PAYMENT_MATCHING;

-- Constraint 6: Single Ongoing Trip per Driver
DROP TRIGGER IF EXISTS DRIVER_ONGOING_CHECK;

-- Constraint 7: Single Ongoing Trip per Passenger
DROP TRIGGER IF EXISTS PASSENGER_ONGOING_CHECK;

-- Constraint 8
DROP TRIGGER IF EXISTS VALID_LICENSE_VEHICLE_REGISTRATION;

-- Constraint 10
DROP TRIGGER IF EXISTS TRIP_ASSIGNMENT_MODE;

-- Constraint: Vehicle capacity and transport mode compatibility
DROP TRIGGER IF EXISTS VALIDATE_VEHICLE_MODE_CATEGORIZATION;

-- Missing semantic constraint triggers
DROP TRIGGER IF EXISTS TRIP_DISCOUNT_BEFORE_INSERT;

DROP TRIGGER IF EXISTS TRIP_DISCOUNT_BEFORE_UPDATE;

DROP TRIGGER IF EXISTS TRIP_BEFORE_UPDATE_DISCOUNT_VALIDITY;

DROP TRIGGER IF EXISTS DISCOUNT_BEFORE_UPDATE_USAGE_AND_VALIDITY;

DROP TRIGGER IF EXISTS PAYMENT_TRANSACTION_BEFORE_INSERT;

DROP TRIGGER IF EXISTS PAYMENT_TRANSACTION_BEFORE_UPDATE;

DROP TRIGGER IF EXISTS COMPLETED_TRIP_BEFORE_UPDATE_PAYMENT_TIME;

DROP TRIGGER IF EXISTS VALIDATE_FINAL_PRICE_CALCULATION;

DROP TRIGGER IF EXISTS INITIALIZE_TRIP_PRICE;

DROP TRIGGER IF EXISTS RECALCULATE_PRICE_ON_DISCOUNT_LINK;

DROP TRIGGER IF EXISTS ASSIGNED_TRIP_BEFORE_INSERT_TIME_CHECK;

DROP TRIGGER IF EXISTS ASSIGNED_TRIP_BEFORE_UPDATE_TIME_CHECK;

DROP TRIGGER IF EXISTS COMPLETED_TRIP_BEFORE_INSERT_TIME_CHECK;

DROP TRIGGER IF EXISTS COMPLETED_TRIP_BEFORE_UPDATE_TIME_CHECK;

DROP PROCEDURE IF EXISTS INSERT_VEHICLE;

DROP PROCEDURE IF EXISTS SWITCH_VEHICLE;

DROP PROCEDURE IF EXISTS DELETE_VEHICLE;

DROP PROCEDURE IF EXISTS GET_DRIVER_VEHICLE_LIST;

DROP PROCEDURE IF EXISTS GET_PASSENGER_MONTHLY_REPORT;

DROP PROCEDURE IF EXISTS GET_PASSENGER_TRIP_HISTORY;

DROP PROCEDURE IF EXISTS GET_DRIVER_TRIP_HISTORY;

DROP PROCEDURE IF EXISTS REFRESH_TRIP_FINAL_PRICE;

DROP PROCEDURE IF EXISTS SIGN_UP_DRIVER;

DROP PROCEDURE IF EXISTS SIGN_UP_PASSENGER;

DROP PROCEDURE IF EXISTS GET_USER_INFO;

DROP FUNCTION IF EXISTS SIGN_IN;

DROP FUNCTION IF EXISTS GRAB_COIN_BONUS;

DROP FUNCTION IF EXISTS CALCULATE_DRIVER_BONUS_FEE;

-- 1. Drop many-to-many relationship and multivalued attribute tables
DROP TABLE IF EXISTS ACCOUNT_COMMUNICATION;
-- [cite: 1355]
DROP TABLE IF EXISTS TRIP_DISCOUNT;
-- [cite: 1354]
DROP TABLE IF EXISTS VEHICLE_CATEGORIZATION;
-- [cite: 1353]
DROP TABLE IF EXISTS ACCOUNT_NOTIFICATION;
-- [cite: 1352]

-- 2. Drop tables representing specialization subclasses and weak entities
DROP TABLE IF EXISTS SAVED_LOCATION;
-- [cite: 1350]
DROP TABLE IF EXISTS PAYMENT_TRANSACTION;
-- [cite: 1348]
DROP TABLE IF EXISTS COMPLETED_TRIP;
-- [cite: 1346]
DROP TABLE IF EXISTS CANCELLED_TRIP;
-- [cite: 1345]
DROP TABLE IF EXISTS ASSIGNED_TRIP;
-- [cite: 1344]

-- 3. Drop tables for primary entities and recursive relationships
DROP TABLE IF EXISTS TRIP;
-- [cite: 1343]
DROP TABLE IF EXISTS VEHICLE;
-- [cite: 1342]
DROP TABLE IF EXISTS BANK_ACCOUNT;
-- [cite: 1341]
DROP TABLE IF EXISTS PAYMENT_METHOD;
-- [cite: 1340]
DROP TABLE IF EXISTS REFERRAL;
-- [cite: 1351]
DROP TABLE IF EXISTS DRIVER;
-- [cite: 1338]
DROP TABLE IF EXISTS PASSENGER;
-- [cite: 1337]

-- 4. Drop base independent entities and configuration tables
DROP TABLE IF EXISTS USER_NOTIFICATION;
-- [cite: 1339]
DROP TABLE IF EXISTS TRANSPORT_MODE;
-- [cite: 1347]
DROP TABLE IF EXISTS DISCOUNT;
-- [cite: 1349]
DROP TABLE IF EXISTS USER_ACCOUNT;
-- [cite: 1336]