USE GRAB;

DROP TRIGGER IF EXISTS BEFORE_DRIVER_INSERT;

DROP TRIGGER IF EXISTS BEFORE_PASSENGER_INSERT;

DROP TRIGGER IF EXISTS BEFORE_ASSIGNED_INSERT;

DROP TRIGGER IF EXISTS BEFORE_CANCELLED_INSERT;

DROP TRIGGER IF EXISTS PREVENT_LAST_VEHIClE_DELETE;

DROP TRIGGER IF EXISTS PREVENT_LAST_BANK_ACCOUNT_DELETE;

DROP TRIGGER IF EXISTS PREVENT_LAST_ACCOUNT_NOTIFICATION_DELETE;

DROP TRIGGER IF EXISTS PREVENT_LAST_VEHICLE_CATEGORIZATION_DELETE;

DROP TRIGGER IF EXISTS PREVENT_TRANSACTION_DELETE;

DROP TRIGGER IF EXISTS update_driver_star_after_insert;

DROP TRIGGER IF EXISTS update_driver_star_after_update;

DROP TRIGGER IF EXISTS update_driver_star_after_delete;

DROP TRIGGER IF EXISTS TRIP_STATUS_ORDER;

DROP TRIGGER IF EXISTS GRABCOIN_ACCUMULATION;

-- Constraint 5: Exact Fare Payment Matching
DROP TRIGGER IF EXISTS FARE_PAYMENT_MATCHING;

-- Constraint 6: Single Ongoing Trip per Driver
DROP TRIGGER IF EXISTS DRIVER_ONGOING_CHECK;

-- Constraint 7: Single Ongoing Trip per Passenger
DROP TRIGGER IF EXISTS PASSENGER_ONGOING_CHECK;

-- Constraint 8
DROP TRIGGER IF EXISTS VALID_LICENSE_VEHICLE_REGISTRATION;

-- Constraint 10
DROP TRIGGER IF EXISTS TRIP_ASSIGNMENT_MODE;

DROP PROCEDURE IF EXISTS INSERT_VEHICLE;

DROP PROCEDURE IF EXISTS SWITCH_VEHICLE;

DROP PROCEDURE IF EXISTS DELETE_VEHICLE;

DROP FUNCTION IF EXISTS GRAB_COIN_BONUS;

-- 1. Drop many-to-many relationship and multivalued attribute tables
DROP TABLE IF EXISTS ACCOUNT_COMMUNICATION;
-- [cite: 1355]
DROP TABLE IF EXISTS TRIP_DISCOUNT;
-- [cite: 1354]
DROP TABLE IF EXISTS VEHICLE_CATEGORIZATION;
-- [cite: 1353]
DROP TABLE IF EXISTS ACCOUNT_NOTIFICATION;
-- [cite: 1352]

-- 2. Drop tables representing specialization subclasses and weak entities
DROP TABLE IF EXISTS SAVED_LOCATION;
-- [cite: 1350]
DROP TABLE IF EXISTS PAYMENT_TRANSACTION;
-- [cite: 1348]
DROP TABLE IF EXISTS COMPLETED_TRIP;
-- [cite: 1346]
DROP TABLE IF EXISTS CANCELLED_TRIP;
-- [cite: 1345]
DROP TABLE IF EXISTS ASSIGNED_TRIP;
-- [cite: 1344]

-- 3. Drop tables for primary entities and recursive relationships
DROP TABLE IF EXISTS TRIP;
-- [cite: 1343]
DROP TABLE IF EXISTS VEHICLE;
-- [cite: 1342]
DROP TABLE IF EXISTS BANK_ACCOUNT;
-- [cite: 1341]
DROP TABLE IF EXISTS PAYMENT_METHOD;
-- [cite: 1340]
DROP TABLE IF EXISTS REFERRAL;
-- [cite: 1351]
DROP TABLE IF EXISTS DRIVER;
-- [cite: 1338]
DROP TABLE IF EXISTS PASSENGER;
-- [cite: 1337]

-- 4. Drop base independent entities and configuration tables
DROP TABLE IF EXISTS USER_NOTIFICATION;
-- [cite: 1339]
DROP TABLE IF EXISTS TRANSPORT_MODE;
-- [cite: 1347]
DROP TABLE IF EXISTS DISCOUNT;
-- [cite: 1349]
DROP TABLE IF EXISTS USER_ACCOUNT;
-- [cite: 1336]