CREATE SCHEMA IF NOT EXISTS GRAB;

USE GRAB;

-- User management
CREATE TABLE IF NOT EXISTS ACCOUNT (
    ACCOUNT_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    PHONE_NUMBER VARCHAR(10) UNIQUE NOT NULL,
    EMAIL VARCHAR(10) UNIQUE NOT NULL,
    ACCOUNT_PASSWORD TEXT NOT NULL,
    GENDER VARCHAR(10),
    AVATAR VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ACCOUNT_COMMUNICATION (
    ACCOUNT_ID INT,
    COMMUNICATION_TYPE VARCHAR(50),
    PRIMARY KEY (ACCOUNT_ID, COMMUNICATION_TYPE),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ACCOUNT_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PASSENGER (
    ACCOUNT_ID INT PRIMARY KEY,
    GRABCOINS INT DEFAULT 0,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ACCOUNT_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DRIVER (
    ACCOUNT_ID INT PRIMARY KEY,
    DRIVER_LICENSE_GRADE VARCHAR(2) NOT NULL,
    CURRENT_BALANCE INT DEFAULT 0,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ACCOUNT_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS REFERRAL (
    DRIVER_ID INT PRIMARY KEY,
    REFERRER_ID INT,
    FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER (ACCOUNT_ID) ON DELETE CASCADE,
    FOREIGN KEY (REFERRER_ID) REFERENCES DRIVER (ACCOUNT_ID) ON DELETE SET NULL
);

-- Supporting entities
CREATE TABLE IF NOT EXISTS BANK_ACCOUNT (
    BANK_ACCOUNT_ID INT AUTO_INCREMENT PRIMARY KEY,
    BANK_NAME VARCHAR(50) NOT NULL,
    ACCOUNT_NUMBER VARCHAR(20) NOT NULL,
    DRIVER_ID INT NOT NULL,
    FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER (ACCOUNT_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SAVED_LOCATION (
    PASSENGER_ID INT,
    SUGGESTIVE_NAME INT,
    ADDRESS VARCHAR(255) NOT NULL,
    COORDINATE_X DECIMAL(15, 4),
    COORDINATE_Y DECIMAL(15, 4),
    PRIMARY KEY (PASSENGER_ID, SUGGESTIVE_NAME),
    FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER (ACCOUNT_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS NOTIFICATION (
    NOTIFICATION_ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT TEXT,
    TIME DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS ACCOUNT_NOTIFICATION (
    ACCOUNT_ID INT,
    NOTIFICATION_ID INT,
    PRIMARY KEY (ACCOUNT_ID, NOTIFICATION_ID),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ACCOUNT_ID) ON DELETE CASCADE,
    FOREIGN KEY (NOTIFICATION_ID) REFERENCES NOTIFICATION (NOTIFICATION_ID) ON DELETE CASCADE
);

-- Transportation and vehicle
CREATE TABLE IF NOT EXISTS VEHICLE (
    VEHICLE_ID INT AUTO_INCREMENT PRIMARY KEY,
    PLATE_NUMBER VARCHAR(20) UNIQUE NOT NULL,
    MAKE VARCHAR(20),
    MODEL VARCHAR(20),
    COLOR VARCHAR(10),
    CAPACITY INT,
    REGISTRANT_ID INT,
    USING_DRIVER_ID INT UNIQUE,
    FOREIGN KEY (REGISTRANT_ID) REFERENCES DRIVER (ACCOUNT_ID) ON DELETE CASCADE,
    FOREIGN KEY (USING_DRIVER_ID) REFERENCES DRIVER (ACCOUNT_ID)
);

CREATE TABLE IF NOT EXISTS TRANSPORT_MODE (
    MODE_ID INT AUTO_INCREMENT PRIMARY KEY,
    TYPE ENUM('Bike', 'Car') NOT NULL,
    SEAT_CAPACITY INT NOT NULL,
    SERVICE_LEVEL ENUM(
        'Standard',
        'Saver',
        'Electric'
    ) NOT NULL
);

CREATE TABLE IF NOT EXISTS VEHICLE_CATEGORIZATION (
    VEHICLE_ID INT,
    MODE_ID INT,
    PRIMARY KEY (VEHICLE_ID, MODE_ID),
    FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE (VEHICLE_ID) ON DELETE CASCADE,
    FOREIGN KEY (MODE_ID) REFERENCES TRANSPORT_MODE (MODE_ID) ON DELETE RESTRICT
);

-- Trips and transactions
CREATE TABLE IF NOT EXISTS TRIP (
    TRIP_ID INT AUTO_INCREMENT PRIMARY KEY,
    FROM_ADDRESS VARCHAR(255),
    FROM_X DECIMAL(15, 4),
    FROM_Y DECIMAL(15, 4),
    TO_ADDRESS VARCHAR(255),
    TO_X DECIMAL(15, 4),
    TO_Y DECIMAL(15, 4),
    BOOKING_TIME DATETIME,
    STATUS VARCHAR(20) NOT NULL,
    PICKUP_INFO TEXT,
    ESTIMATED_PRICE INT,
    USED_GRABCOINS INT DEFAULT 0,
    FINAL_PRICE INT,
    PASSENGER_ID INT NOT NULL,
    MODE_ID INT NOT NULL,
    BOOKING_TYPE ENUM('Standard', 'Scheduled') NOT NULL,
    REQUEST_TIME DATETIME, -- For scheduled trips
    FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER (ACCOUNT_ID),
    FOREIGN KEY (MODE_ID) REFERENCES TRANSPORT_MODE (MODE_ID)
);

CREATE TABLE IF NOT EXISTS ASSIGNED_TRIP (
    TRIP_ID INT PRIMARY KEY,
    FROM_TIME DATETIME,
    DRIVER_ID INT,
    FOREIGN KEY (TRIP_ID) REFERENCES TRIP (TRIP_ID),
    FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER (ACCOUNT_ID)
);

CREATE TABLE IF NOT EXISTS CANCELLED_TRIP (
    TRIP_ID INT PRIMARY KEY,
    CANCELLATION_REASION TEXT,
    FOREIGN KEY (TRIP_ID) REFERENCES TRIP (TRIP_ID)
);

CREATE TABLE IF NOT EXISTS COMPLETED_TRIP (
    TRIP_ID INT PRIMARY KEY,
    TO_TIME DATETIME,
    OBTAINED_GRABCOIN INT DEFAULT 0,
    RATING_STARS INT,
    FEEDBACK TEXT,
    DRIVER_PAY TEXT,
    FOREIGN KEY (TRIP_ID) REFERENCES ASSIGNED_TRIP (TRIP_ID),
    CONSTRAINT RATING_RANGE CHECK (
        RATING_STARS >= 1
        AND RATING_STARS <= 5
    )
);

CREATE TABLE IF NOT EXISTS PAYMENT_METHOD (
    PAYMENT_METHOD_ID INT AUTO_INCREMENT PRIMARY KEY,
    TYPE VARCHAR(20) NOT NULL,
    ACCOUNT_IDENTIFIER VARCHAR(50) NOT NULL,
    PASSENGER_ID INT NOT NULL,
    FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER (ACCOUNT_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TRANSACTION (
    TRANSACTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    PAYMENT_AMOUNT INT NOT NULL,
    DATE_TIME DATETIME NOT NULL,
    PAID_BY_CASH BOOLEAN DEFAULT FALSE,
    TIP INT DEFAULT 0,
    TRIP_ID INT UNIQUE NOT NULL,
    PAYMENT_METHOD_ID INT,
    FOREIGN KEY (TRIP_ID) REFERENCES COMPLETED_TRIP (TRIP_ID),
    FOREIGN KEY (PAYMENT_METHOD_ID) REFERENCES PAYMENT_METHOD (PAYMENT_METHOD_ID)
);