-- Active: 1775061495821@@127.0.0.1@3306@grab
CREATE SCHEMA IF NOT EXISTS GRAB;
USE GRAB;

-- User management
CREATE TABLE IF NOT EXISTS USER_ACCOUNT (
    ACCOUNT_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    PHONE_NUMBER VARCHAR(10) UNIQUE NOT NULL,
    EMAIL VARCHAR(50) UNIQUE NOT NULL,
    ACCOUNT_PASSWORD TEXT NOT NULL,
    GENDER VARCHAR(10),
    AVATAR VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ACCOUNT_COMMUNICATION (
    ACCOUNT_ID INT,
    COMMUNICATION_TYPE ENUM(
        'Email',
        'SMS',
        'Push Notification'
    ) NOT NULL,
    PRIMARY KEY (
        ACCOUNT_ID,
        COMMUNICATION_TYPE
    ),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES USER_ACCOUNT (ACCOUNT_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PASSENGER (
    ACCOUNT_ID INT PRIMARY KEY,
    GRABCOINS INT DEFAULT 0,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES USER_ACCOUNT (ACCOUNT_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DRIVER (
    ACCOUNT_ID INT PRIMARY KEY,
    DRIVER_LICENSE_GRADE VARCHAR(2) NOT NULL,
    CURRENT_BALANCE INT DEFAULT 0,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES USER_ACCOUNT (ACCOUNT_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS REFERRAL (
    DRIVER_ID INT PRIMARY KEY,
    REFERRER_ID INT,
    FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER (ACCOUNT_ID) ON DELETE CASCADE,
    FOREIGN KEY (REFERRER_ID) REFERENCES DRIVER (ACCOUNT_ID) ON DELETE SET NULL
);

-- Supporting entities
CREATE TABLE IF NOT EXISTS BANK_ACCOUNT (
    BANK_ACCOUNT_ID INT AUTO_INCREMENT PRIMARY KEY,
    BANK_NAME VARCHAR(50) NOT NULL,
    ACCOUNT_NUMBER VARCHAR(20) NOT NULL,
    DRIVER_ID INT NOT NULL,
    FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER (ACCOUNT_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SAVED_LOCATION (
    PASSENGER_ID INT,
    SUGGESTIVE_NAME VARCHAR(255),
    ADDRESS VARCHAR(255) NOT NULL,
    COORDINATE_X DECIMAL(10, 7), -- X from -180 to 180
    COORDINATE_Y DECIMAL(9, 7), -- Y from -90 to 90
    PRIMARY KEY (PASSENGER_ID, SUGGESTIVE_NAME),
    FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER (ACCOUNT_ID) ON DELETE CASCADE,
    CONSTRAINT VALID_COORDINATES CHECK (
        COORDINATE_X BETWEEN -180 AND 180
        AND COORDINATE_Y BETWEEN -90 AND 90
    )
);

CREATE TABLE IF NOT EXISTS USER_NOTIFICATION (
    NOTIFICATION_ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT TEXT,
    TIME DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS ACCOUNT_NOTIFICATION (
    ACCOUNT_ID INT,
    NOTIFICATION_ID INT,
    PRIMARY KEY (ACCOUNT_ID, NOTIFICATION_ID),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES USER_ACCOUNT (ACCOUNT_ID) ON DELETE CASCADE,
    FOREIGN KEY (NOTIFICATION_ID) REFERENCES USER_NOTIFICATION (NOTIFICATION_ID) ON DELETE CASCADE
);

-- Transportation and vehicle
CREATE TABLE IF NOT EXISTS VEHICLE (
    VEHICLE_ID INT AUTO_INCREMENT PRIMARY KEY,
    PLATE_NUMBER VARCHAR(20) UNIQUE NOT NULL,
    MAKE VARCHAR(20),
    MODEL VARCHAR(20),
    COLOR VARCHAR(10),
    CAPACITY INT,
    REGISTRANT_ID INT,
    USING_DRIVER_ID INT UNIQUE,
    FOREIGN KEY (REGISTRANT_ID) REFERENCES DRIVER (ACCOUNT_ID) ON DELETE CASCADE,
    FOREIGN KEY (USING_DRIVER_ID) REFERENCES DRIVER (ACCOUNT_ID) ON DELETE CASCADE,
    CONSTRAINT MINIMUM_CAPACITY_VEHICLE CHECK (CAPACITY >= 1),
    CONSTRAINT USING_DRIVER CHECK (
        (USING_DRIVER_ID IS NULL)
        OR (
            USING_DRIVER_ID = REGISTRANT_ID
        )
    )
);

CREATE TABLE IF NOT EXISTS TRANSPORT_MODE (
    MODE_ID INT AUTO_INCREMENT PRIMARY KEY,
    TYPE ENUM('Bike', 'Car') NOT NULL,
    SEAT_CAPACITY INT NOT NULL,
    SERVICE_LEVEL ENUM(
        'Standard',
        'Saver',
        'Electric'
    ) NOT NULL,
    CONSTRAINT MINIMUM_CAPACITY_MODE CHECK (SEAT_CAPACITY >= 1)
);

CREATE TABLE IF NOT EXISTS VEHICLE_CATEGORIZATION (
    VEHICLE_ID INT,
    MODE_ID INT,
    PRIMARY KEY (VEHICLE_ID, MODE_ID),
    FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE (VEHICLE_ID) ON DELETE CASCADE,
    FOREIGN KEY (MODE_ID) REFERENCES TRANSPORT_MODE (MODE_ID) ON DELETE CASCADE
);

-- Trips and transactions
CREATE TABLE IF NOT EXISTS TRIP (
    TRIP_ID INT AUTO_INCREMENT PRIMARY KEY,
    FROM_ADDRESS VARCHAR(255),
    FROM_X DECIMAL(10, 7),
    FROM_Y DECIMAL(9, 7),
    TO_ADDRESS VARCHAR(255),
    TO_X DECIMAL(10, 7),
    TO_Y DECIMAL(9, 7),
    BOOKING_TIME DATETIME,
    STATUS ENUM(
        'PENDING',
        'ASSIGNED',
        'DRIVER_ARRIVED',
        'ONGOING',
        'COMPLETED',
        'CANCELLED'
    ) NOT NULL,
    PICKUP_INFO TEXT,
    ESTIMATED_PRICE INT,
    USED_GRABCOINS INT DEFAULT 0,
    FINAL_PRICE INT,
    PASSENGER_ID INT NOT NULL,
    MODE_ID INT NOT NULL,
    BOOKING_TYPE ENUM('Standard', 'Scheduled') NOT NULL,
    REQUEST_TIME DATETIME, -- For scheduled trips
    FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER (ACCOUNT_ID),
    FOREIGN KEY (MODE_ID) REFERENCES TRANSPORT_MODE (MODE_ID),
    CONSTRAINT TRIP_TOTAL_SPECIALIZATION CHECK (
        (
            BOOKING_TYPE = 'Standard'
            AND REQUEST_TIME IS NULL
        )
        OR (
            BOOKING_TYPE = 'Scheduled'
            AND (
                REQUEST_TIME IS NOT NULL
                AND TIMESTAMPDIFF(
                    MINUTE,
                    REQUEST_TIME,
                    BOOKING_TIME
                ) >= 75
            )
        )
    ),
    CONSTRAINT NON_NEGATIVE_VALUES_TRIP CHECK (
        ESTIMATED_PRICE >= 0
        AND FINAL_PRICE >= 0
        AND USED_GRABCOINS >= 0
    ),
    CONSTRAINT VALID_FROM_COORDS CHECK (
        FROM_X BETWEEN -180 AND 180
        AND FROM_Y BETWEEN -90 AND 90
    ),
    CONSTRAINT VALID_TO_COORDS CHECK (
        TO_X BETWEEN -180 AND 180
        AND TO_Y BETWEEN -90 AND 90
    ),
    CONSTRAINT TRIP_MUST_MOVE CHECK (
        FROM_X <> TO_X
        OR FROM_Y <> TO_Y
    )
);

CREATE TABLE IF NOT EXISTS ASSIGNED_TRIP (
    TRIP_ID INT PRIMARY KEY,
    FROM_TIME DATETIME,
    DRIVER_ID INT,
    FOREIGN KEY (TRIP_ID) REFERENCES TRIP (TRIP_ID) ON DELETE CASCADE,
    FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER (ACCOUNT_ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS CANCELLED_TRIP (
    TRIP_ID INT PRIMARY KEY,
    CANCELLATION_REASON TEXT,
    FOREIGN KEY (TRIP_ID) REFERENCES TRIP (TRIP_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS COMPLETED_TRIP (
    TRIP_ID INT PRIMARY KEY,
    TO_TIME DATETIME,
    OBTAINED_GRABCOIN INT DEFAULT 0,
    RATING_STARS INT,
    FEEDBACK TEXT,
    DRIVER_PAY INT,
    FOREIGN KEY (TRIP_ID) REFERENCES ASSIGNED_TRIP (TRIP_ID) ON DELETE CASCADE,
    CONSTRAINT RATING_RANGE CHECK (RATING_STARS BETWEEN 1 AND 5),
    CONSTRAINT NON_NEGATIVE_VALUES_COMPLETED CHECK (OBTAINED_GRABCOIN >= 0)
);

CREATE TABLE IF NOT EXISTS PAYMENT_METHOD (
    PAYMENT_METHOD_ID INT AUTO_INCREMENT PRIMARY KEY,
    TYPE ENUM('E-Wallet', 'Card') NOT NULL,
    ACCOUNT_IDENTIFIER VARCHAR(50) NOT NULL,
    PASSENGER_ID INT NOT NULL,
    FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER (ACCOUNT_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PAYMENT_TRANSACTION (
    TRANSACTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    PAYMENT_AMOUNT INT NOT NULL,
    DATE_TIME DATETIME NOT NULL,
    PAID_BY_CASH BOOLEAN DEFAULT FALSE,
    TIP INT DEFAULT 0,
    TRIP_ID INT UNIQUE NOT NULL,
    PAYMENT_METHOD_ID INT,
    FOREIGN KEY (TRIP_ID) REFERENCES COMPLETED_TRIP (TRIP_ID) ON DELETE CASCADE,
    FOREIGN KEY (PAYMENT_METHOD_ID) REFERENCES PAYMENT_METHOD (PAYMENT_METHOD_ID) ON DELETE SET NULL,
    CONSTRAINT NON_NEGATIVE_VALUES_TRANSACTION CHECK (PAYMENT_AMOUNT >= 0)
);

-- Discount
CREATE TABLE IF NOT EXISTS DISCOUNT (
    DISCOUNT_ID INT AUTO_INCREMENT PRIMARY KEY,
    MAX_USAGE INT,
    VALID_UNTIL_DATE DATETIME,
    DISCOUNT_TYPE ENUM('Percentage', 'Amount') NOT NULL,
    PERCENTAGE_DISCOUNT DECIMAL(10, 4),
    AMOUNT_DISCOUNT INT,
    CONSTRAINT DISCOUNT_TOTAL_SPECIALIZATION CHECK (
        (
            (
                DISCOUNT_TYPE = 'Percentage'
                AND (
                    PERCENTAGE_DISCOUNT IS NOT NULL
                    AND PERCENTAGE_DISCOUNT >= 0
                )
                AND AMOUNT_DISCOUNT IS NULL
            )
        )
        OR (
            DISCOUNT_TYPE = 'Amount'
            AND PERCENTAGE_DISCOUNT IS NULL
            AND (
                AMOUNT_DISCOUNT IS NOT NULL
                AND AMOUNT_DISCOUNT >= 0
            )
        )
    )
);

CREATE TABLE IF NOT EXISTS TRIP_DISCOUNT (
    TRIP_ID INT,
    DISCOUNT_ID INT,
    PRIMARY KEY (TRIP_ID, DISCOUNT_ID),
    FOREIGN KEY (TRIP_ID) REFERENCES TRIP (TRIP_ID) ON DELETE CASCADE,
    FOREIGN KEY (DISCOUNT_ID) REFERENCES DISCOUNT (DISCOUNT_ID) ON DELETE CASCADE
);

-- EERD related triggers
DELIMITER //

-- Prevent a Passenger from being registered as a Driver
CREATE TRIGGER BEFORE_DRIVER_INSERT
BEFORE INSERT ON DRIVER
FOR EACH ROW

BEGIN
    IF EXISTS (SELECT 1 FROM PASSENGER WHERE ACCOUNT_ID = NEW.ACCOUNT_ID) THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Disjoint Constraint Violated: Account is already a Passenger.';
    END IF;
END//

-- Prevent a Driver from being registered as a Passenger
CREATE TRIGGER BEFORE_PASSENGER_INSERT
BEFORE INSERT ON PASSENGER
FOR EACH ROW
BEGIN
    IF EXISTS (SELECT 1 FROM DRIVER WHERE ACCOUNT_ID = NEW.ACCOUNT_ID) THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Disjoint Constraint Violated: Account is already a Driver.';
    END IF;
END//

-- Prevent inserting an assigned trip to canceleld trip table
CREATE TRIGGER BEFORE_ASSIGNED_INSERT
BEFORE INSERT ON ASSIGNED_TRIP
FOR EACH ROW
BEGIN
    IF EXISTS (SELECT 1 FROM CANCELLED_TRIP WHERE TRIP_ID = NEW.TRIP_ID) THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Disjoint Constraint Violated: Trip is already cancelled.';
    END IF;
END//

-- Prevent inserting a cancelled trip to assigned trip table
CREATE TRIGGER BEFORE_CANCELLED_INSERT
BEFORE INSERT ON CANCELLED_TRIP
FOR EACH ROW
BEGIN
    IF EXISTS (SELECT 1 FROM ASSIGNED_TRIP WHERE TRIP_ID = NEW.TRIP_ID) THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Disjoint Constraint Violated: Trip is already assigned.';
    END IF;
END//

-- Prevent a driver from deleting the last vehicle
CREATE TRIGGER PREVENT_LAST_VEHICLE_DELETE
BEFORE DELETE ON VEHICLE
FOR EACH ROW
BEGIN
    DECLARE vehicle_count INT;
    SELECT COUNT(*) INTO vehicle_count FROM VEHICLE WHERE REGISTRANT_ID = OLD.REGISTRANT_ID;
    
    IF vehicle_count <= 1 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Total Participation Violated: Driver must register at least one vehicle.';
    END IF;
END//

-- Prevent a driver from deleting the last bank account
CREATE TRIGGER PREVENT_LAST_BANK_ACCOUNT_DELETE
BEFORE DELETE ON BANK_ACCOUNT
FOR EACH ROW
BEGIN
    DECLARE account_count INT;
    SELECT COUNT(*) INTO account_count FROM BANK_ACCOUNT B WHERE DRIVER_ID = OLD.DRIVER_ID;
    
    IF account_count <= 1 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Total Participation Violated: Driver must have at least one bank account.';
    END IF;
END//

CREATE TRIGGER PREVENT_TRANSACTION_DELETE
BEFORE DELETE ON PAYMENT_TRANSACTION
FOR EACH ROW
BEGIN
    DECLARE trip_count INT;
    SELECT COUNT(*) INTO trip_count FROM COMPLETED_TRIP WHERE TRIP_ID = OLD.TRIP_ID;

    IF trip_count > 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Total Participation Violated: A completed trip must have a payment transaction.';
    END IF;
END//

-- Prevent a notification from losing its last account association
CREATE TRIGGER PREVENT_LAST_ACCOUNT_NOTIFICATION_DELETE
BEFORE DELETE ON ACCOUNT_NOTIFICATION
FOR EACH ROW
BEGIN
    DECLARE notification_count INT;
    SELECT COUNT(*) INTO notification_count FROM ACCOUNT_NOTIFICATION WHERE NOTIFICATION_ID = OLD.NOTIFICATION_ID;

    IF notification_count <= 1 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Total Participation Violated: A notification must be sent to at least one account.';
    END IF;
END//

-- Prevent a vehicle from losing its last categorization
CREATE TRIGGER PREVENT_LAST_VEHICLE_CATEGORIZATION_DELETE
BEFORE DELETE ON VEHICLE_CATEGORIZATION
FOR EACH ROW
BEGIN
    DECLARE mode_count INT;
    SELECT COUNT(*) INTO mode_count FROM VEHICLE_CATEGORIZATION WHERE VEHICLE_ID = OLD.VEHICLE_ID;

    IF mode_count <= 1 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Total Participation Violated: A vehicle must be categorized into at least one trasnport mode.';
    END IF;
END//

DELIMITER ;